### ISSUE TITLE
Composer install throws doctrine exception with notification bundle version 2.2.*@dev

### ISSUE THREAD

**Issue by cdwlighting** [sonata-project/SonataNotificationBundle#109]
[Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\NotificationBundle\Controller\Api\MessageController::getMessagesAction() does not exist, or could not be auto-loaded.

If Nelmio/ApiDocBundle is required, it should be in the composer.json file, and the documentation should be updated to reflect setting up this bundle.

**Comment by core23** [comment]
The ``ApiDocBundle`` is optional now. So I'll close this.
