### ISSUE TITLE
sonata notification bundle 

### ISSUE THREAD

**Issue by aymentrabelsi** [sonata-project/SonataNotificationBundle#119]
i want to ask if sonata NotificationBundle is avaible for symfony 2.4 
because config mapping is autoloded in symfony 2.4 
i don't know where to put (entity_managers:
            default:
                    # ...
                mappings:
                    # ...
                    SonataNotificationBundle: ~
                    ApplicationSonataNotificationBundle: ~)

**Comment by core23** [comment]
You can use this with symfony 2.3+. Please have a look at the docs https://sonata-project.org/bundles/notification/master/doc/index.html
