### ISSUE TITLE
KO! - The property om does not exists ?

### ISSUE THREAD

**Issue by vishalmelmatti** [sonata-project/SonataNotificationBundle#120]
I have sonata notification bundle 2.2.5 version installed. It was working fine but now suddenly started giving this error in below command

sonata:notification:start --type=mailer 

The error seems to be in Sonata\NotificationBundle\Entity\MessageManager as $this->om->getUnitOfWork() is used. 

This seems to be incompatible with  https://github.com/sonata-project/SonataCoreBundle/blob/master/Model/BaseEntityManager.php

**Comment by OskarStark** [comment]
@vishalmelmatti is this fixed in the meantime? which version you are using right now?

Oskar

**Comment by vishalmelmatti** [comment]
Yeah it is fixed. Thanks
