### ISSUE TITLE
multiple backends or custom multiple backends

### ISSUE THREAD

**Issue by jjbier** [sonata-project/SonataNotificationBundle#125]
Hello, It is possible use multiple backends or for the backends rabbitmq multiple exchange. 

Thanks .

**Comment by core23** [comment]
Can you provide a PR? @jjbier

**Comment by vishalmelmatti** [comment]
+1 I need to use multiple backends e.g. rabbitmq for email notifications and doctrine for in app messages.

**Comment by core23** [comment]
Feel free to start contributing to supply this feature @vishalmelmatti
