### ISSUE TITLE
Make MessageManagerMessageIterator in MessageManagerBackend configurable 

### ISSUE THREAD

**Issue by hasc** [sonata-project/SonataNotificationBundle#130]
Hey,

first thanks for sharing this bundle!

I would like to provide a custom implementation of the MessageManagerMessageIterator. Since currently this class is created directly within the MessageManagerBackend->getIterator() it is hard to do so.

Exposing this class as a service and injecting it into the backend would be perfect.

Please let me know it this is possible. Also please let me know if you want me to provide an implementation (pull request).

Kind regards
Hannes

**Comment by core23** [comment]
I don't get the concrete use case, but feel free to supply a PR.

**Comment by jordisala1991** [comment]
No use case provided, closing for now.

If you want to reopen, please provide a use case.
