### ISSUE TITLE
Doctrine backend message queue iterator order

### ISSUE THREAD

**Issue by warriorGod** [sonata-project/SonataNotificationBundle#146]
I have noticed an issue where messages are not being processed in the order they are put in. This is how I would expect the queue to work: FIFO

Upon inspection it looks like message iterator is picking a few messages (bufferSize) and doing array_pop on them. This doesn't sound ok to me? Am I missing something?

Regards,
Gregor

**Comment by core23** [comment]
The order depends on the used messaging backend. Which backend are you using?
