### ISSUE TITLE
Detached messages are duplicated by the MessageManager

### ISSUE THREAD

**Issue by excursions** [sonata-project/SonataNotificationBundle#147]
-<b>Description</b>

If MessageManager::save() encounters a detached <code>$message</code> it tries to merge it:

<code>$this->getEntityManager()->getUnitOfWork()->merge($message);</code>

This code returns a <b>new</b> managed instance, but it is not assigned to <code>$message</code>.

Thus the old, unmanaged version of the message is passed down and persisted when calling:
<code>parent::save($message, $andFlush)</code>

This results in a duplicate entry of the message.

-<b>Steps to reproduce</b>

To reproduce this I set up the bundle with doctrine (using the default connection and entity manger). 
With this setup calling <code>$em->clear()</code> during ConsumerInterface::process() results in a duplicate message (in DB) for each processed message

-<b>Proposed solution</b>

I reckon this should do the trick:

<code>$message = $this->getEntityManager()->getUnitOfWork()->merge($message);</code>

**Comment by core23** [comment]
Feel free to create a PR @excursions
