### ISSUE TITLE
SonataEasyExtendsBundle not included by default in Notification

### ISSUE THREAD

**Issue by franciscop** [sonata-project/SonataNotificationBundle#160]
I had to manually add the bundle to the AppKernel while [installing the Notification bundle](https://sonata-project.org/bundles/notification/master/doc/reference/installation.html):

``` php
new Sonata\EasyExtendsBundle\SonataEasyExtendsBundle(),
```

However that is undocumented in the previously linked file. I think the Notification bundle should include it automatically OR it should be noted in the documentation. I didn't edit the documentation directly since it might be a bug in the bundle instead of a documentation issue.

**Comment by OskarStark** [comment]
no this is not directly a dependency, it is more a helper bundle which generates the needed stuff, so a doc change PR would be :+1:

**Comment by pborreli** [comment]
agree with @OskarStark it should not be a dependency as you can totally use this bundle without extending anything. 👍 for a doc PR
