### ISSUE TITLE
Get rid of Guzzle depencency

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataNotificationBundle#182]
The Guzzle client is only used here: https://github.com/sonata-project/SonataNotificationBundle/blob/6489ea52510033e3de2e4d997eba20528f9548e3/Backend/AMQPBackendDispatcher.php#L172-L184

This is quite cumbersome to require a big library like guzzle just for do only one request (without service usage BTW).

Plus, you are using Guzzle 3 that is deprecated from a looong time.

It would be great to use a light library or why not just curl.

Or maybe use the php-http abstraction: http://docs.php-http.org/en/latest/integrations/symfony-bundle.html

As guzzle is used internally, requirement drop can be done a new minor.

**Comment by greg0ire** [comment]
> Or maybe use the php-http abstraction: http://docs.php-http.org/en/latest/integrations/symfony-bundle.html

:+1:

**Comment by VincentLanglet** [comment]
Closing since we plan to abandon this project.
