### ISSUE TITLE
Show backend in profiler

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataNotificationBundle#228]
Maybe we could use the profiler to show backend calls.

<img width="211" alt="bildschirmfoto 2017-01-28 um 14 51 08" src="https://cloud.githubusercontent.com/assets/3440437/22397068/41717abe-e569-11e6-89d1-9383754e34d5.PNG">

**Comment by OskarStark** [comment]
Nice idea!

**Comment by VincentLanglet** [comment]
Closing since we plan to abandon this project.
