### ISSUE TITLE
ContainerAwareEventDispatcher deprecated

### ISSUE THREAD

**Issue by KDederichs** [sonata-project/SonataNotificationBundle#247]
## Subject

Starting Symfony the use of Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher is deprecated and will give the following warning: 
The Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher class is deprecated since version 3.3 and will be removed in 4.0. Use EventDispatcher with closure factories instead:

It would be beneficial if this old interface could be swapped with the new one

## Steps to reproduce

Install sonata notification with Symfony 3.3

## Expected results

No warnings on unit tests

## Actual results

The Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher class is deprecated since version 3.3 and will be removed in 4.0. Use EventDispatcher with closure factories instead:

**Comment by core23** [comment]
Can you please provide a PR with a fix @KDederichs ?
