### ISSUE TITLE
[rfc] Migration to AMQP interop

### ISSUE THREAD

**Issue by makasim** [sonata-project/SonataNotificationBundle#275]
Would you be interested to migrate to [amqp interop](https://github.com/queue-interop/queue-interop#amqp-interop). 

The biggest advantage among others is that it would work with php-amqplib, amqp-ext, and bunny libraries. 

If you are fine with it I can work on a PR.

**Comment by greg0ire** [comment]
@makasim sure, that would be great!

**Comment by makasim** [comment]
@greg0ire could you take a look at https://github.com/sonata-project/SonataNotificationBundle/pull/276

If that looks good to you I'll continue working on it.

**Comment by greg0ire** [comment]
Sure thing! Thanks a lot!
