### ISSUE TITLE
php 7.2 The each() function is deprecated 

### ISSUE THREAD

**Issue by LaxCorp** [sonata-project/SonataNotificationBundle#306]
The each() function is deprecated in php 7.2.

Please fix: sonata-project/notification-bundle/src/Backend/PostponeRuntimeBackend.php
line 82
while (list($key, $message) = each($this->messages)) {
         $this->handle($message, $this->dispatcher);
}

on

foreach($this->messages as $key => $message){
         $this->handle($message, $this->dispatcher);
}

**Comment by OskarStark** [comment]
would you like to create PR?
