### ISSUE TITLE
Snapshot generation command does not work anymore

### ISSUE THREAD

**Issue by psyray** [sonata-project/SonataNotificationBundle#310]
See https://github.com/sonata-project/SonataPageBundle/issues/950

Problem comes from sonata-page command `sonata:page:create-snapshots --site=all`, but errors seems to come from sonata-notification.
So my issue is in the sonata-page github page.

Reported here only for information, feel free to delete or close it if it's not the right place.

**Comment by jordisala1991** [comment]
Fixed already

**Comment by gremo** [comment]
Release please? Or we should continue to use this buggy release?

**Comment by greg0ire** [comment]
It's planned
