### ISSUE TITLE
Running tasks simultaneously

### ISSUE THREAD

**Issue by jo66** [sonata-project/SonataNotificationBundle#373]
## Feature Request

Would be nice to have ability to run tasks all together and not one by one, when `sonata:notification:start` is called... but maybe I'm a dreamer?

**Comment by core23** [comment]
Feel free to add this feature!

**Comment by jo66** [comment]
At least I can try... Any suggestion on how to proceed?

**Comment by core23** [comment]
AFAIK the only way to do this is to start new PHP processes. But keep in mind, that PHP is not Java or any other language that was designed to start many async operations.

**Comment by jo66** [comment]
I created a command to consume one message specified by its id. This is working. But when I replace code in ConsumerHandler to call my command instead of handling it directly, result is that it's called a lot, I guess until first call finished.
Any idea how to prevent it?
I can try to understand better how backend iterate on messages to find a solution, but I'd like at least to know if my approach is good... what do you think?

**Comment by greg0ire** [comment]
:thinking: why not simply use supervisord, runit or whatever to start as many consumers as you need, instead of reinventing it php?

**Comment by jo66** [comment]
Problem is that I don't know how much I need :-/

**Comment by greg0ire** [comment]
1 per CPU?

**Comment by jo66** [comment]
@greg0ire Thanks a lot for your answers!
It's very light processes, as they will just make calls to an API and wait between, but they will be triggered by user action so it can be a lot, and I don't want to run a huge amount of useless processes to be "sure" that it will be enough...
But maybe I should change my approach and decompose processes, so they won't wait? But it will be more complicated architecture.
Instead of reinventing wheel, maybe I should give a try to JMSJobQueueBundle, any experience with it?

**Comment by greg0ire** [comment]
Nope… but keep in mind that one consumer will be enough, it might be slow, but no messages will be dropped. So it's not about being sure that it will be enough, and more about being sure that it will be fast enough.

**Comment by jo66** [comment]
@greg0ire I decided to change my logic not to use too much processes, I think it's more reliable like that, so thanks!

**Comment by greg0ire** [comment]
You're very welcome!
