### ISSUE TITLE
Stop using ContainerAwareCommand in commands

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataNotificationBundle#464]
## Feature Request

Use dependency injection instead of extending `ContainerAwareCommand`.

The `sonata.notification.erroneous_messages_selector` service should be made private again.

Refs: https://github.com/sonata-project/SonataNotificationBundle/pull/458#discussion_r464437890

**Comment by VincentLanglet** [comment]
Done in https://github.com/sonata-project/SonataNotificationBundle/pull/490 and https://github.com/sonata-project/SonataNotificationBundle/pull/583
