### ISSUE TITLE
Monitoring worker scripts

### ISSUE THREAD

**Issue by pulse00** [sonata-project/SonataNotificationBundle#90]
This is rather a question than an issue: Are there any best practices on how to monitor worker scripts? E.g. check if they still respond and work correctly? We're using `supervisord` to run the workers, but have already had some situations where supervisord has reported the consumer as `running`, but the consumer failed internally.

**Comment by toooni** [comment]
@pulse00 what did you do? we are having an issue where the mysql connection is lost at some point. The commands are executed, but failing with "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away". This does not happen very often so i might add a daily cron job which restarts supervisord.. but this isn't a solution i am very happen with..

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
